[tool.black]
line-length = 120

[tool.isort]
profile = "black"
combine_as_imports = true
combine_star = true
line_length = 120

[tool.pyright]
include = [
    "api/",
    "builder/",
]
exclude = [
    "**/__pycache__",
    "build",
    "dist",
    "docs",
]
reportMissingImports = "none"
reportUnnecessaryTypeIgnoreComment = "warning"
pythonVersion = "3.10"
typeCheckingMode = "basic"