# rename this file to server-config.toml

[users]
superuser-name = "admin"
superuser-password = "password" # change this to be something secure
allow-user-creation = true # when enabled, anyone can create an account.
allow-project-creation = false # this only applies to users who are not the superuser

[api]
host = "0.0.0.0"
port = 1006

[api.postgres]
host = "127.0.0.1"
port = 5432
user = "user"
password = "password"
database = "docity"

[builder]
host = "127.0.0.1"
port = 1007

[frontend]
host = "0.0.0.0"
port = 1008